export const CHAMPION_IMAGE_MAP: Record<string, string> = {
    "Aatrox": "Aatrox.png",
    "Ahri": "Ahri.png",
    "Akali": "Akali.png",
    "Akshan": "Akshan.png",
    "Alistar": "Alistar.png",
    "Ambessa": "Ambessa.png",
    "Amumu": "Amumu.png",
    "Anivia": "Anivia.png",
    "Annie": "Annie.png",
    "Aphelios": "Aphelios.png",
    "Ashe": "Ashe.png",
    "Aurelion Sol": "AurelionSol.png",
    "Aurora": "Aurora.png",
    "Azir": "Azir.png",
    "Bard": "Bard.png",
    "Bel'Veth": "Bel'Veth.png",
    "Blitzcrank": "Blitzcrank.png",
    "Brand": "Brand.png",
    "Braum": "Braum.png",
    "Briar": "Briar.png",
    "Caitlyn": "Caitlyn.png",
    "Camille": "Camille.png",
    "Cassiopeia": "Cassiopeia.png",
    "Cho'Gath": "Chogath.png",
    "Corki": "Corki.png",
    "Darius": "Darius.png",
    "Diana": "Diana.png",
    "Draven": "Draven.png",
    "Dr. Mundo": "DrMundo.png",
    "Ekko": "Ekko.png",
    "Elise": "Elise.png",
    "Evelynn": "Evelynn.png",
    "Ezreal": "Ezreal.png",
    "Fiddlesticks": "Fiddlesticks.png",
    "Fiora": "Fiora.png",
    "Fizz": "Fizz.png",
    "Galio": "Galio.png",
    "Gangplank": "Gangplank.png",
    "Garen": "Garen.png",
    "Gnar": "Gnar.png",
    "Gragas": "Gragas.png",
    "Graves": "Graves.png",
    "Gwen": "Gwen.png",
    "Hecarim": "Hecarim.png",
    "Heimerdinger": "Heimerdinger.png",
    "Hwei": "Hwei.png",
    "Illaoi": "Illaoi.png",
    "Irelia": "Irelia.png",
    "Ivern": "Ivern.png",
    "Janna": "Janna.png",
    "Jarvan IV": "JarvanIV.png",
    "Jax": "Jax.png",
    "Jayce": "Jayce.png",
    "Jhin": "Jhin.png",
    "Jinx": "Jinx.png",
    "Kai'Sa": "Kaisa.png",
    "Kalista": "Kalista.png",
    "Karma": "Karma.png",
    "Karthus": "Karthus.png",
    "Kassadin": "Kassadin.png",
    "Katarina": "Katarina.png",
    "Kayle": "Kayle.png",
    "Kayn": "Kayn.png",
    "Kennen": "Kennen.png",
    "Kha'Zix": "KhaZix.png",
    "Kindred": "Kindred.png",
    "Kled": "Kled.png",
    "Kog'Maw": "KogMaw.png",
    "K'Sante": "K'Sante.png",
    "LeBlanc": "LeBlanc.png",
    "Lee Sin": "LeeSin.png",
    "Leona": "Leona.png",
    "Lillia": "Lillia.png",
    "Lissandra": "Lissandra.png",
    "Lucian": "Lucian.png",
    "Lulu": "Lulu.png",
    "Lux": "Lux.png",
    "Malphite": "Malphite.png",
    "Malzahar": "Malzahar.png",
    "Maokai": "Maokai.png",
    "Master Yi": "MasterYi.png",
    "Mel": "Mel.png",
    "Milio": "Milio.png",
    "Miss Fortune": "MissFortune.png",
    "Wukong": "Wukong.png",
    "Mordekaiser": "Mordekaiser.png",
    "Morgana": "Morgana.png",
    "Naafiri": "Naafiri.png",
    "Nami": "Nami.png",
    "Nasus": "Nasus.png",
    "Nautilus": "Nautilus.png",
    "Neeko": "Neeko.png",
    "Nidalee": "Nidalee.png",
    "Nilah": "Nilah.png",
    "Nocturne": "Nocturne.png",
    "Nunu & Willump": "Nunu.png",
    "Olaf": "Olaf.png",
    "Orianna": "Orianna.png",
    "Ornn": "Ornn.png",
    "Pantheon": "Pantheon.png",
    "Poppy": "Poppy.png",
    "Pyke": "Pyke.png",
    "Qiyana": "Qiyana.png",
    "Quinn": "Quinn.png",
    "Rakan": "Rakan.png",
    "Rammus": "Rammus.png",
    "Rek'Sai": "Rek'Sai.png",
    "Rell": "Rell.png",
    "Renata Glasc": "Renata Glasc.png",
    "Renekton": "Renekton.png",
    "Rengar": "Rengar.png",
    "Riven": "Riven.png",
    "Rumble": "Rumble.png",
    "Ryze": "Ryze.png",
    "Samira": "Samira.png",
    "Sejuani": "Sejuani.png",
    "Senna": "Senna.png",
    "Seraphine": "Seraphine.png",
    "Sett": "Sett.png",
    "Shaco": "Shaco.png",
    "Shen": "Shen.png",
    "Shyvana": "Shyvana.png",
    "Singed": "Singed.png",
    "Sion": "Sion.png",
    "Sivir": "Sivir.png",
    "Skarner": "Skarner.png",
    "Smolder": "Smolder.png",
    "Sona": "Sona.png",
    "Soraka": "Soraka.png",
    "Swain": "Swain.png",
    "Sylas": "Sylas.png",
    "Syndra": "Syndra.png",
    "Tahm Kench": "TahmKench.png",
    "Taliyah": "Taliyah.png",
    "Talon": "Talon.png",
    "Taric": "Taric.png",
    "Teemo": "Teemo.png",
    "Thresh": "Thresh.png",
    "Tristana": "Tristana.png",
    "Trundle": "Trundle.png",
    "Tryndamere": "Tryndamere.png",
    "Twisted Fate": "TwistedFate.png",
    "Twitch": "Twitch.png",
    "Udyr": "Udyr.png",
    "Urgot": "Urgot.png",
    "Varus": "Varus.png",
    "Vayne": "Vayne.png",
    "Veigar": "Veigar.png",
    "Vel'Koz": "VelKoz.png",
    "Vex": "Vex.png",
    "Vi": "Vi.png",
    "Viego": "Viego.png",
    "Viktor": "Viktor.png",
    "Vladimir": "Vladimir.png",
    "Volibear": "Volibear.png",
    "Warwick": "Warwick.png",
    "Xayah": "Xayah.png",
    "Xerath": "Xerath.png",
    "Xin Zhao": "XinZhao.png",
    "Yasuo": "Yasuo.png",
    "Yone": "Yone.png",
    "Yorick": "Yorick.png",
    "Yunara": "Yunara.png",
    "Yuumi": "Yuumi.png",
    "Zac": "Zac.png",
    "Zed": "Zed.png",
    "Zeri": "Zeri.png",
    "Ziggs": "Ziggs.png",
    "Zilean": "Zilean.png",
    "Zoe": "Zoe.png",
    "Zyra": "Zyra.png",
};


export interface ChampionStats {
    name: string;
    image: string;
    role: string;
    tier: string;
    winRate: string;
    pickRate: string;
    banRate: string;
    counterPicks: string[];
    totalMatchesPicked: number;
}

export function mapChampionsWithImages(champions: ChampionStats[]): ChampionStats[] {
  return champions.map(champ => ({
    ...champ,
    image: CHAMPION_IMAGE_MAP[champ.name],
  }));
}
